account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('', views.Home.as_view(), name='home'), 
    path('profile/', views.Profile.as_view(), name='profile'),   

    path('food/list/', views.FoodList.as_view(), name='food_list'), 
    path('food/create/', views.FoodCreate.as_view(), name='food_create'), 
    path('food/update/<int:pk>/', views.FoodUpdate.as_view(), name='food_update'),
    path('food/delete/<int:pk>/', views.FoodDelete.as_view(), name='food_delete'),

    path('category/list/', views.CategoryList.as_view(), name='category_list'), 
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'), 
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', views.CategoryDelete.as_view(), name='category_delete'),
    
    path('employee/list/', views.EmployeeList.as_view(), name='employee_list'), 
    path('employee/create/', views.EmployeeCreate.as_view(), name='employee_create'), 
    path('employee/update/<int:pk>/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', views.EmployeeDelete.as_view(), name='employee_delete'),
    
    path('about/create/', views.AboutCreate.as_view(), name='about_create'), 
    path('about/create/<int:pk>/', views.AboutUpdate.as_view(), name='about_update'),

    path('contact/list/', views.ContactList.as_view(), name='contact_list'), 
    path('contact/detail/<int:pk>/', views.ContactDetail.as_view(), name='contact_detail'), 
    path('contact/delete/<int:pk>/', views.ContactDelete.as_view(), name='contact_delete'),
    path('contact/detail/<int:pk>/', views.ContactDetail.as_view(), name='contact_detail'), 

    path('address/create/', views.AddressCreate.as_view(), name='address_create'), 
    path('address/create/<int:pk>/', views.AddressUpdate.as_view(), name='address_update'),

    path('history/create/', views.HistoryCreate.as_view(), name='history_create'), 
    path('history/create/<int:pk>/', views.HistoryUpdate.as_view(), name='history_update'),

    path('order/list/', views.OrderList.as_view(), name='order_list'),
    path('user_order/list/', views.UserOrderList.as_view(), name='user_order_list'),    
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart_detail/',views.cart_detail,name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate
from django.contrib.auth.views import PasswordChangeForm

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'), 
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('accounts/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('restaurant.urls', namespace='restaurant')), 
    path('tinymce/', include('tinymce.urls')),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/urls.py
from django.urls import path
from . import views


app_name = 'restaurant'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:slug>/', views.CategoryProductListView.as_view(), name='products_by_category'),
    path('about/', views.AboutView.as_view(), name='about'), 
    path('contact/', views.ContactView.as_view(), name='contact'), 
]

restaurant/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from phonenumber_field.modelfields import PhoneNumberField


class SingletonBaseModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

class AvailableManager(models.Manager):
    def get_queryset(self):
        return super(AvailableManager, self).get_queryset().filter(available=True)

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:home_by_category", args=[self.slug])
 
class Food(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(unique=True, db_index=True)
    image = models.ImageField(upload_to="foods/%Y/%m/%d")
    description = HTMLField(blank=True)
    category = models.ForeignKey(Category, related_name='foods', on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    price = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    objects_available = AvailableManager()
    
    class Meta:
        ordering = ('-created', )
        index_together = (('id', 'slug'), ) 

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurant:food_detail', kwargs={'slug': self.slug})
        
class Employee(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='first name')
    last_name = models.CharField(max_length=100, verbose_name='last name')
    image = models.ImageField()
    position = models.CharField(max_length=100)
    description = models.TextField()
    instagram = models.URLField(null=True, blank=True)
    tweeter = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    youtube = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name 
    
    def get_full_name(self):
        return self.first_name + ' ' + self.last_name 
    
class About(SingletonBaseModel):
    description = HTMLField()
    
    def __str__(self) -> str:
        return self.description

class History(SingletonBaseModel):
    description = HTMLField()   

    def __str__(self) -> str:
        return self.description

class Address(SingletonBaseModel):
    description = models.TextField(max_length=200, verbose_name='full address')
    phone_number = PhoneNumberField()
    email = models.EmailField()
    tweeter = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)


    def __str__(self) -> str:
        return self.description

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self) -> str:
        return self.name 

restaurant/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ian somerholder'}), 
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'iansomer@gmail.com'}), 
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'leave your message for us...'}) 
        }

restaurant/views.py
import imp
from django.shortcuts import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import Category, Food, Employee, About, History, Contact, Address
from .forms import ContactForm
from django.contrib import messages
from django.http import JsonResponse


class HomeView(ListView):
    model = Food
    template_name = 'restaurant/home.html'
    context_object_name = 'foods'
    paginate_by = 100  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CategoryProductListView(ListView):
    model = Food
    context_object_name = 'foods'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        if slug == 'all':
            return Food.objects.all()
        category = get_object_or_404(Category, slug=slug)
        return Food.objects.filter(category=category)

    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            foods = context['foods']
            products = [{'id': food.id, 'name': food.name, 'image': food.image.url, 'description': food.description, 'price': food.price} for food in foods]
            return JsonResponse({'products': products})
        return super().render_to_response(context, **response_kwargs)

class AboutView(ListView):
    model = Employee
    template_name = 'restaurant/about.html'
    context_object_name = 'employees'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = About.objects.get(pk=1)
        context['history'] = History.objects.get(pk=1)
        context['active'] = True

        return context

class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'restaurant/contact.html'

    def get_success_url(self) -> str:
        success_message = 'your message was sent to admin.'
        messages.success(self.request, success_message)
        return reverse('restaurant:contact')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['address'] = Address.objects.get(pk=1)
        return context

templates/restaurant/about.html
{% extends 'restaurant/base.html' %}
{% load static %}
{% block title %}About Us{% endblock %}

{% block content %}

    <header class="container mt-5 m-b-5">
        <div class='row justify-content-center'> 
            <h2 class="text-center">About Simple House</h2>
        </div>
        
        <div class='row justify-content-center' style="padding-right:19px"> 
            <p class="text-center">{{ about.description|safe }}</p>
        </div>
    </header>

    <div class="tm-container-inner tm-persons mt-5">
        <div class="row">
            {% for employee in employees %}
                <article class="col-sm-12 col-md-6 col-lg-6">
                    <figure class="tm-person">
                        <img src="{{ employee.image.url }}" alt="Image" class="img-fluid tm-person-img" />
                        <figcaption class="tm-person-description">
                            <h4 class="tm-person-name">{{ employee }}</h4>
                            <p class="tm-person-title">{{ employee.position }}</p>
                            <p class="tm-person-about">{{ employee.description|safe }}</p>
                            <div>
                                <a href="{{ employee.facebook }}" class="tm-social-link"><i class="fab fa-facebook tm-social-icon"></i></a>
                                <a href="{{ employee.twitter }}" class="tm-social-link"><i class="fab fa-twitter tm-social-icon"></i></a>
                                <a href="{{ employee.instagram }}" class="tm-social-link"><i class="fab fa-instagram tm-social-icon"></i></a>
                            </div>
                        </figcaption>
                    </figure>
                </article>
            {% endfor %}
        </div>
    </div>
    <div class="tm-container-inner tm-featured-image">
        <div class="row">
            <div class="col-12">
                <div class="placeholder-2">
                    <div class="parallax-window-2" data-parallax="scroll" data-image-src="{% static 'img/about-05.jpg' %}"></div>		
                </div>
            </div>
        </div>
    </div>
 
    <div class="tm-container-inner tm-history">
        <div class="row">
            <div class="col-12">
                <div class="tm-history-inner">
                    
                    <img src="{% static 'img/about-06.jpg' %}" alt="Image" class="img-fluid tm-history-img" />
                    <div class='tm-history-text'>
                        <h4 class="tm-history-title">History of our restaurant</h4>
                        <div class="tm-history-text"> 
                            <p>
                            {{ history.description|safe }}
                            </p>
                        </div>
                    </div>
                </div>	
            </div>
        </div>
    </div>
{% endblock %}

templates/restaurant/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title%}Restaurant{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />    
	<link href="{% static 'css/templatemo-style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link src="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/toastr.css' %}">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>

<body> 
	{% include './messages.html' %}

	<div class="container">
		<!-- Logo & Site Name -->
		<div class="placeholder">
			<div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'img/simple-house-01.jpg' %}">
				<div class="tm-header">
					<div class="row tm-header-inner">
						<div class="col-md-6 col-12">
							<img src="{% static 'img/simple-house-logo.png' %}" alt="Logo" class="tm-site-logo" /> 
							<div class="tm-site-text-box">
								<h1 class="tm-site-title">Simple House</h1>
								<h6 class="tm-site-description">the best restaurant</h6>	
							</div>
						</div>
						<nav class="col-md-6 col-12 tm-nav">
							<ul class="tm-nav-ul">
								<li class="tm-nav-li"><a href="{% url 'restaurant:home' %}" class="tm-nav-link {% if request.resolver_match.url_name == "home" %}active{% endif %}">Home</a></li>
								<li class="tm-nav-li"><a href="{% url 'restaurant:about' %}" class="tm-nav-link {% if request.resolver_match.url_name == "about" %}active{% endif %}">About</a></li>
								<li class="tm-nav-li"><a href="{% url 'restaurant:contact' %}" class="tm-nav-link {% if request.resolver_match.url_name == "contact" %}active{% endif %}">Contact</a></li>
								<li class="tm-nav-li"><a href="{% url 'cart:cart_detail' %}" class="tm-nav-link {% if request.resolver_match.url_name == "cart:cart_detail" %}active{% endif %}">Cart</a></li>
								<li class="tm-nav-li"><a href="{% url 'account:profile' %}" class="tm-nav-link {% if request.resolver_match.url_name == "account:profile" %}active{% endif %}">Profile</a></li>
							</ul>
						</nav>	
					</div>
				</div>
			</div>
		</div>
		<main>
			{% block content %}

			{% endblock content %}
		</main>
		<footer class="tm-footer text-center">
			<p>Copyright &copy; 2020 Simple House 
            
            | Design: <a rel="nofollow" href="https://templatemo.com">TemplateMo</a></p>
		</footer>
	</div>	
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/parallax.min.js' %}"></script>
	

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="{% static 'js/toastr.min.js' %}"></script>
	<script>
		{% comment %}  messags  {% endcomment %}
        if ($(window).width() < 768) {
            function notify(message, type) {
                $.growl({
                    message: message
                }, {
                    type: type,
                    allow_dismiss: false,
                    label: 'Cancel',
                    className: 'btn-xs btn-inverse',
                    placement: {
                        from: 'top',
                        align: 'center'
                    },
                    delay: 5000,
                    animate: {
                        enter: 'animated fadeInUp',
                        exit: 'animated fadeOutUp'
                    },
                    offset: {
                        x: 30,
                        y: 30
                    }
                });
            };
         }
         else {
            function notify(message, type) {
                $.growl({
                    message: message
                }, {
                    type: type,
                    allow_dismiss: false,
                    label: 'Cancel',
                    className: 'btn-xs btn-inverse',
                    placement: {
                        from: 'bottom',
                        align: 'left'
                    },
                    delay: 6000,
                    animate: {
                        enter: 'animated fadeInUp',
                        exit: 'animated fadeOutDown'
                    },
                    offset: {
                        x: 30,
                        y: 30
                    }
                });
            };
         }
        {% if messages %}
        {% for message in messages %}
            notify('{{ message }}', '{{ message.tags }}');
        {% endfor %}
        {% endif %}
	</script>
    {% block js %}

    {% endblock %}
</body>
</html>

templates/restaurant/contact.html
{% extends 'restaurant/base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role='alert'>
                {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <header class="row d-flex justify-content-center mb-4 mt-4 p-3">
        <h2 class="col-12 text-center tm-section-title">Contact Page</h2>
        <p class="col-12 text-center">You may use <a rel="nofollow" href="https://www.ltcclock.com/downloads/simple-contact-form/" target="_blank">Simple Contact Form</a> to send email to your inbox. You can modify and use this template for your website. Header image has a parallax effect. Total 3 HTML pages included in this template.</p>
    </header>

    <div class="tm-container-inner-2 tm-contact-section">
        <div class="row">
            <div class="col-md-6">
                <form action="" method="POST" class="tm-contact-form">
                   {% csrf_token %}
                   {{ form.as_p }}
                   <input type='submit' class='btn btn-success'>
                </form>
            </div>
            <div class="col-md-6">
                <div class="tm-address-box">
                    <h4 class="tm-info-title tm-text-success">Our Address</h4>
                    <address>
                        {{ address.description|safe }}
                    </address>
                    <a href="tel:{{ address.phone_number }}" class="tm-contact-link">
                        <i class="fas fa-phone tm-contact-icon"></i>{{ address.phone_number }}
                    </a>
                    <a href="mailto:info@company.co" class="tm-contact-link">
                        <i class="fas fa-envelope tm-contact-icon"></i> {{ address.email }}
                    </a>
                    <div class="tm-contact-social">
                        <a href="{{ address.facebook }}" class="badge badge-success badge-pill"><i class="fab fa-facebook"></i></a>
                        <a href="{{ address.twitter }}" class="badge badge-success badge-pill"><i class="fab fab fa-twitter"></i></a>
                        <a href="{{ address.instagram }}" class="badge badge-success badge-pill"><i class="fab fa-instagram"></i></a>

                        {% comment %} <a href="{{ address.facebook }}" class="tm-social-link"><i class="fab fa-facebook tm-social-icon"></i></a> {% endcomment %}
                        {% comment %} <a href="{{ address.twitter }}" class="tm-social-link"><i class="fab fa-twitter tm-social-icon"></i></a> {% endcomment %}
                        {% comment %} <a href="{{ address.instagram }}" class="tm-social-link"><i class="fab fa-instagram tm-social-icon"></i></a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<!-- How to change your own map point
1. Go to Google Maps
2. Click on your location point
3. Click "Share" and choose "Embed map" tab
4. Copy only URL and paste it within the src="" field below
-->
    <div class="tm-container-inner-2 tm-map-section">
        <div class="row">
            <div class="col-12">
                <div class="tm-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11196.961132529668!2d-43.38581128725845!3d-23.011063013218724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9bdb695cd967b7%3A0x171cdd035a6a9d84!2sAv.%20L%C3%BAcio%20Costa%20-%20Barra%20da%20Tijuca%2C%20Rio%20de%20Janeiro%20-%20RJ%2C%20Brazil!5e0!3m2!1sen!2sth!4v1568649412152!5m2!1sen!2sth" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/restaurant/home.html
{% extends 'restaurant/base.html' %}

{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <header class="row d-flex justify-content-center mb-4 mt-4 p-3">
        <h2 class="text-center tm-section-title display-4 text-primary">Welcome to Simple House</h2>
        <p class="text-center text-muted">Explore our delicious menu across a variety of categories. Enjoy a seamless experience as you switch between categories without reloading the page!</p>
    </header>

    <!-- Category Navigation -->
    <div class="d-flex justify-content-center mb-4">
        <nav>
            <ul id="category-list" class="nav nav-pills">
                <a href="#" class="nav-link category-btn btn-outline-success mb-2" data-slug="all">
                    all
                </a>
                {% for cat in categories %}
                    <li class="nav-item">
                        <a href="#" class="nav-link category-btn btn-outline-success mb-2" data-slug="{{ cat.slug }}">
                            {{ cat.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </nav>
    </div>

    <!-- Product Grid -->
    <div class="container">
        <div class='row' id="products-list">
            {% for food in foods %}
            <div class="col-sm-6 col-md-4 col-lg-3 d-flex align-items-stretch mb-4">
                <div class='card shadow-sm border-0'>
                    <div class='card-header p-0 position-relative'>
                        <img class="card-img-top rounded-top" src="{{ food.image.url }}" style='height: 200px; width: 240px; object-fit: cover;' alt="image for {{ food.name }}">
                        <span class="badge badge-success position-absolute" style="top: 10px; right: 10px;">${{ food.price }}</span>
                    </div>

                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title text-center font-weight-bold text-dark">{{ food.name }}</h5>
                        <p class="card-text text-muted text-truncate">{{ food.description|safe }}</p>
                    </div>

                    <div class='card-footer bg-transparent border-0'>
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted small">Price: ${{ food.price }}</span>
                            <a href="#" class="btn btn-outline-primary btn-sm btn-add-to-cart" data-url="{% url 'cart:cart_add' food.id %}">
                                <i class="fas fa-cart-plus"></i> Add to Cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

{% block js %}
<!-- SweetAlert2 CSS and JS -->
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        // Add product to cart
        $(document).on('click', '.btn-add-to-cart', function(e) {
            e.preventDefault();
            var addToCartUrl = $(this).data('url'); 

            $.ajax({
                url: addToCartUrl,  
                method: 'GET',
                success: function(response) {
                    Swal.fire({
                        title: 'Added to Cart!',
                        text: response.message,
                        icon: 'success',
                        showConfirmButton: false,
                        timer: 1500
                    });
                },
                error: function(xhr, status, error) {
                    Swal.fire({
                        title: 'Error',
                        text: 'Failed to add product to cart. Please try again.',
                        icon: 'error',
                    });
                }
            });
        });

        // Handle category switching
        $('.category-btn').click(function(e) {
            e.preventDefault();
            var slug = $(this).data('slug');

            var url = "{% url 'restaurant:products_by_category' 'dummy-slug' %}".replace('dummy-slug', slug);

            $.ajax({
                url: url,
                method: 'GET',
                success: function(response) {
                    var productsHtml = '';
                    if (response.products && response.products.length > 0) {
                        response.products.forEach(function(product) {
                            productsHtml += `
                            <div class="col-sm-6 col-md-4 col-lg-3 d-flex align-items-stretch mb-4">
                                <div class='card shadow-sm border-0'>
                                    <div class='card-header p-0 position-relative'>
                                        <img class="card-img-top rounded-top" src="${product.image}" style='height: 200px; width: 240px; object-fit: cover;' alt="image for ${product.name}">
                                        <span class="badge badge-success position-absolute" style="top: 10px; right: 10px;">${product.price} $</span>
                                    </div>
                                    <div class="card-body d-flex flex-column justify-content-between">
                                        <h5 class="card-title text-center font-weight-bold text-dark">${product.name}</h5>
                                        <p class="card-text text-muted text-truncate">${product.description}</p>
                                    </div>
                                    <div class='card-footer bg-transparent border-0'>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <span class="text-muted small">Price: ${product.price} $</span>
                                            <a href="#" class="btn btn-outline-primary btn-sm btn-add-to-cart" data-url="/cart/add/${product.id}/">
                                                <i class="fas fa-cart-plus"></i> Add to Cart
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>`;
                        });
                    } else {
                        productsHtml = '<p>No products available in this category.</p>';
                    }
                    $('#products-list').html(productsHtml);
                },
                error: function() {
                    Swal.fire({
                        title: 'Error',
                        text: 'An error occurred while loading the products.',
                        icon: 'error',
                    });
                }
            });
        });
    });
</script>
{% endblock %}

templates/restaurant/messages.html
{% if messages %}
    <div class="notification-container">
        {% for message in messages %}
            <div class="notification alert-{{ message.tags }}">
                <span class="notification-icon">
                    {% if message.tags == 'success' %}
                        ✔️
                    {% elif message.tags == 'warning' %}
                        ⚠️
                    {% elif message.tags == 'error' %}
                        ❌
                    {% elif message.tags == 'info' %}
                        ℹ️
                    {% endif %}
                </span>
                <span class="notification-message">{{ message }}</span>
                <button class="close-btn" onclick="this.parentElement.style.display='none';">×</button>
            </div>
        {% endfor %}
    </div>  
{% endif %}